# Supabase Configuration File

[project]
name = "restaurantecubano"
region = "us-east-1"

[database]
port = 5432
version = "15"

[auth]
site_url = "http://localhost:3000"
additional_redirect_urls = ["http://localhost:3000/**"]

[auth.email]
enable_signup = true
double_confirm_changes = true
enable_confirmations = true

[auth.sms]
enable_signup = false
twilio_sid = ""
twilio_token = ""
twilio_from = ""

[auth.external.google]
enabled = true
client_id = "your-google-client-id"
secret = "your-google-secret"

[auth.external.facebook]
enabled = false
client_id = ""
secret = ""

[storage]
file_size_limit = "50MiB"

[functions]
verify_jwt = true